### ISSUE TITLE
IndexError: list index out of range

### ISSUE THREAD

**Issue by JamesHoi** [JamesHoi/Open163-Downloader#3]
Traceback (most recent call last):
  File "main.py", line 206, in <module>
  File "main.py", line 173, in main
  File "main.py", line 29, in getOldVersion
IndexError: list index out of range
[3140] Failed to execute script main

**Comment by JamesHoi** [comment]
网易公开课已不支持电脑观看视频，此软件已无法使用
https://www.zhihu.com/question/401103254

但我还是找到了能下载视频的方法，我有时间我会修改软件的

**Comment by JamesHoi** [comment]
网易公开课已更新网页,现已支持网页版观看视频
