### ISSUE TITLE
如果只有高清的视频，会找不到路径

### ISSUE THREAD

**Issue by Tester-Dolores** [JamesHoi/Open163-Downloader#7]
视频 ：https://open.163.com/newview/movie/free?pid=M7GHICM7G&mid=M9OSGHOLI
报错：
```
Traceback (most recent call last):
  File "D:\download\python3.9\lib\site-packages\threadpool.py", line 158, in run
    result = request.callable(*request.args, **request.kwds)
  File "E:\Open163-Downloader-1.2.0\main.py", line 36, in download_video
    download_file(video[key],path,head+video["title"]+" - "+dic[quality]+".mp4")
  File "E:\Open163-Downloader-1.2.0\common.py", line 7, in download_file
    r = requests.get(url, stream=True,verify=False)
  File "D:\download\python3.9\lib\site-packages\requests\api.py", line 76, in get
    return request('get', url, params=params, **kwargs)
  File "D:\download\python3.9\lib\site-packages\requests\api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "D:\download\python3.9\lib\site-packages\requests\sessions.py", line 528, in request
    prep = self.prepare_request(req)
  File "D:\download\python3.9\lib\site-packages\requests\sessions.py", line 456, in prepare_request
    p.prepare(
  File "D:\download\python3.9\lib\site-packages\requests\models.py", line 316, in prepare
    self.prepare_url(url, params)
  File "D:\download\python3.9\lib\site-packages\requests\models.py", line 390, in prepare_url
    raise MissingSchema(error)
requests.exceptions.MissingSchema: Invalid URL '': No schema supplied. Perhaps you meant http://?
```
以下是我打印接口响应结果
```
{'mid': 'M7GHJFM24', 'plid': 'M7GHICM7G', 'title': '清华大学公开课：《大学生心理健康》我的生涯我做主（
一）', 'mLength': 2005, 'imgPath': 'http://open-image.ws.126.net/697ea37d45694fdd82079a9e6b868e65.jpg'
, 'pNumber': 1, 'commentId': None, 'subtitle': '中文', 'subtitleLanguage': '中文', 'webUrl': 'https://
open.163.com/movie/2011/10/2/4/M7GHICM7G_M7GHJFM24.html', 'shortWebUrl': 'http://c.open.163.com/mob/video.htm?plid=M7GHICM7G&mid=M7GHJFM24#share-mob', 'hits': 1492632, 'iosShow': 1, 'protoVersion': 1, 'mp4SdSize': 0, 'mp4HdSize': 71057732, 'mp4ShdSize': 0, 'mp4SdSizeOrign': 0, 'mp4HdSizeOrign': 0, 'mp4ShdSizeOrign': 0, 'm3u8SdSize': 0, 'm3u8HdSize': 0, 'm3u8ShdSize': 0, 'm3u8SdSizeOrign': 0, 'm3u8HdSizeOrign': 0, 'm3u8ShdSizeOrign': 0, 'mp4SdUrl': '', 'mp4HdUrl': 'http://mov.bn.netease.com/mobilev/2011/11/2/2/S7HB8R222.mp4', 'mp4ShdUrl': '', 'mp4SdUrlOrign': '', 'mp4HdUrlOrign': '', 'mp4ShdUrlOrign': '', 'm3u8SdUrl': '', 'm3u8HdUrl': 'http://mov.bn.netease.com/movie/2011/11/2/2/S7HB8R222-list.m3u8', 'm3u8ShdUrl': '', 'm3u8SdUrlOrign': '', 'm3u8HdUrlOrign': '', 'm3u8ShdUrlOrign': '', 'mp4ShareUrl': 'http://mov.bn.netease.com/mobilev/2011/11/2/2/S7HB8R222.mp4', 'airPlayInfos': [], 'subList': [], 'advInfo': {'advSource': 1, 'advPreId': None, 'advMidId': None, 'advPosId': None}, 'isStore': False, 'movieId': None, 'isCollect': 0, 'courseListKey': None, 'mtype': 0, 'isDefaultPlan': False, 'description': '本节课
主要内容包括：什么是生涯规划？为什么要做生涯规划？怎样做生涯规划？'}
mp4SdUrlOrign
path:
url:
```

我自己改了下`main.py` 的 103行，但是没有经过更详细测试,不确定是否会有其他问题，你看看怎么改更合适....
`notice = "检测到有画质 "; qualities = []; video = data["videoList"][current_episode]`

**Comment by Tester-Dolores** [comment]
会有问题， 如果选择的是16集。 你看下怎么改合适。。我就不研究了。。。

**Comment by JamesHoi** [comment]
确实当时写的非常烂...我也知道有哪些bug，主要是没时间修改
